### ISSUE TITLE
NullPointerException thrown when no config file is provided (with OpenJDK 16)

### ISSUE THREAD

**Issue by cthlo** [Azure/autorest.java#1222]
With OpenJDK 16, the following is thrown during generation if no config file is provided:
```
fatal   | Postprocessor | Unhandled error: Cannot invoke "String.length()" because "this.input" is null
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
        at java.base/java.net.URI$Parser.parse(URI.java:3157)
        at java.base/java.net.URI.<init>(URI.java:623)
        at com.azure.autorest.postprocessor.Postprocessor.processInternal(Postprocessor.java:50)
        at com.azure.autorest.extension.base.plugin.NewPlugin.process(NewPlugin.java:206)
        at com.azure.autorest.postprocessor.Main.lambda$main$1(Main.java:12)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$dispatch$2(Connection.java:152)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$process$3(Connection.java:271)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

fatal   | Process() cancelled due to failure
error   |   Error: Plugin postprocessor reported failure.
```

Java version:
```
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Microsoft-25298 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Microsoft-25298 (build 16.0.2+7, mixed mode, sharing)
```

`new URI(null)` in this OpenJDK build:
```
jshell> import java.net.URI;
jshell> new URI(null)
|  Exception java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
|        at URI$Parser.parse (URI.java:3157)
|        at URI.<init> (URI.java:623)
|        at (#4:1)
```

Maybe a null check here as well?
https://github.com/Azure/autorest.java/blob/812f325a3859dba8755810a96dec85348deefa28/postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java#L50

**Comment by weidongxu-microsoft** [comment]
I guess the fix should be a simple check on NPE?

However I am in the impression that the readme.md (the same one in project root) will always be found and used, if no other readme.md provided.

**Comment by weidongxu-microsoft** [comment]
It had to, without the block of `use`, nothing will ever run,.
https://github.com/Azure/autorest.java/blob/main/readme.md#javagen-1

Anyway, I will add a NPE protection there.
