### ISSUE TITLE
Java DataPlane SDK generation failure with error error "java.util.NoSuchElementException: No value present"

### ISSUE THREAD

**Issue by bhargav-kansagara** [Azure/autorest.java#1703]
I'm trying to generate Java SDK on top of [DataPlane Swagger](https://github.com/Azure/azure-rest-api-specs/blob/2969d7b53325b54b61fa827f2dfb85a0df9f82d0/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2021-07-31-preview/agfood.json) but I'm getting the below error:

`error   | Javagen | Failed to generate code.
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at com.azure.autorest.mapper.ClientMethodMapper.createClientMethods(ClientMethodMapper.java:378)
        at com.azure.autorest.mapper.ClientMethodMapper.map(ClientMethodMapper.java:110)
        at com.azure.autorest.mapper.ClientMethodMapper.map(ClientMethodMapper.java:100)
        at com.azure.autorest.mapper.MethodGroupMapper.createMethodGroupClient(MethodGroupMapper.java:122)
        at com.azure.autorest.mapper.MethodGroupMapper.map(MethodGroupMapper.java:44)
        at com.azure.autorest.mapper.ServiceClientMapper.map(ServiceClientMapper.java:120)
        at com.azure.autorest.mapper.ClientMapper.map(ClientMapper.java:143)
        at com.azure.autorest.Javagen.processInternal(Javagen.java:83)
        at com.azure.autorest.extension.base.plugin.NewPlugin.process(NewPlugin.java:210)
        at com.azure.autorest.Main.lambda$main$1(Main.java:15)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$dispatch$2(Connection.java:141)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$process$3(Connection.java:245)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

fatal   | Process() cancelled due to failure
error   |   Error: Plugin javagen reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.`

Client generation for python, C# & js is working fine, I'm getting this error only in Java client generation. I have tried autorest command `autorest --version=3.8.4 --use=@autorest/java@4.1.3 sdk\agrifood\azure-verticals-agrifood-farming\swagger\README.md` as well as python script `python eng\mgmt\automation\generate_data.py --readme=C:\Users\bhargav-kansagara\azure-sdk-for-java\sdk\agrifood\azure-verticals-agrifood-farming\swagger\README.md` but no success.

Could you please let me know if I'm doing anything wrong here? Thanks in advance.

**Comment by weidongxu-microsoft** [comment]
@bhargav-kansagara 

Please remove these 2 options in swagger/README.md
```
generate-client-interfaces: false
sync-methods: none
```

Please note that the current DPG is totally different from the lib that generated years ago. So almost all files will be different.

Ref https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods

**Comment by bhargav-kansagara** [comment]
Thanks for the help, that solved the issue.
