### ISSUE TITLE
[BUG] Autorest not working for directories with spaces Java

### ISSUE THREAD

**Issue by ibrahimrabab** [Azure/autorest.java#1802]
Hi there,

I'm trying to use Autorest for Java but cannot run it properly due to spaces in the directory where it is installed.
When I run `autorest --java` , it installs autorest 4.1.6 but then fails to execute with the following error:

`error   |   Error: Unable to resolve package 'file:///C:/Users/Rabab%20Ibrahim/.autorest/@autorestjava@4.1.6/nodemodules/@autorest/java/javagen'.`
Screenshots included from command line:
![image](https://user-images.githubusercontent.com/88855721/197306841-2dcadc53-4a44-4aea-90f5-ab1b8703588c.png)

![image](https://user-images.githubusercontent.com/88855721/197306761-14ab474c-daab-48da-9145-0cc8bec6fa6d.png)

Looks like the directory path replaces spaces with `%20` symbols which is why it is unable to run autorest in the location it was downloaded. Is there an anticipated fix for this or some way I can run autorest properly?

Thanks!
![Screenshot 2022-10-21 170411](https://user-images.githubusercontent.com/88855721/197307026-44b0668a-a184-4115-b2b8-c0656143551b.png)
![Screenshot 2022-10-21 170916](https://user-images.githubusercontent.com/88855721/197307027-e49b6dec-7285-4535-ac61-f123bcfb1e96.png)

**Comment by weidongxu-microsoft** [comment]
Would you try running "autorest --reset" once, before this command?

**Comment by ibrahimrabab** [comment]
Hi @weidongxu-microsoft 
I ran `autorest --reset` and then ran `autorest --java` right after, but it did not fix the problem.

![image](https://user-images.githubusercontent.com/88855721/197606070-08565b2a-e5a9-4451-8a18-4cac15c3abb0.png)

**Comment by weidongxu-microsoft** [comment]
You can use "AUTOREST_HOME" env variable to change the folder that autorest installs the plugins. Use it to point somewhere where there is no space.

This seems to be a bug on autorest.

**Comment by ibrahimrabab** [comment]
So I set AUTOREST_HOME and ran autorest --java which I believe ran 4.1.6, but then I see the following error:
`error   | Postprocessor | Failed to complete postprocessing.
java.lang.RuntimeException: java.lang.RuntimeException: Failed to build with status code WITH_ERROR
        at com.azure.autorest.postprocessor.Postprocessor.loadCustomizationClass(Postprocessor.java:258)
        at com.azure.autorest.postprocessor.Postprocessor.loadCustomizationClassFromJavaCode(Postprocessor.java:217)
        at com.azure.autorest.postprocessor.Postprocessor.processInternal(Postprocessor.java:118)
        at com.azure.autorest.extension.base.plugin.NewPlugin.process(NewPlugin.java:212)
        at com.azure.autorest.postprocessor.Main.lambda$main$1(Main.java:15)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$dispatch$2(Connection.java:141)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$process$3(Connection.java:245)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Failed to build with status code WITH_ERROR
        at com.azure.autorest.postprocessor.Postprocessor.loadCustomizationClass(Postprocessor.java:256)
        ... 11 more`

![image](https://user-images.githubusercontent.com/88855721/197708606-5eb44418-046d-432c-8c85-5a5e32f5a642.png)

Is this an issue with the way autorest is installed on my machine?

**Comment by weidongxu-microsoft** [comment]
Workaround provided via "AUTOREST_HOME" env variable.
