### ISSUE TITLE
com.google.googlejavaformat.java.FormatterException on generating classes for azur deviceupdate

### ISSUE THREAD

**Issue by dermoritz** [Azure/autorest.java#1870]
Not really sure if this is a problem in API spec or in Autogen/java:
I cloned https://github.com/Azure/azure-rest-api-specs tried to generate classes for 

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceupdate/resource-manager/Microsoft.DeviceUpdate/stable/2022-10-01/deviceupdate.json

with this command:

```
autorest --java 
         --use:@autorest/java@4.1.9 
         --input-file:"C:\Users\moritz\code\azure-rest-api-specs\specification\deviceupdate\resource-manager\Microsoft.DeviceUpdate\stable\2022-10-01\deviceupdate.json" 
         --output-folder:./azure-api-gen-test 
         --namespace:here.for.me
```

This error appears

```
warning | Deprecated | seal-single-value-enum-by-default is a temporary flag that WILL be removed in the future. Please change the spec to add x-ms-enum.modelAsString=false for enums with this issue.
error   | Javagen | Unable to format output file src/main/java/here/for/me/models/PublicNetworkAccess.java
com.google.googlejavaformat.java.FormatterException: 1:15: error: <identifier> expected
        at com.google.googlejavaformat.java.FormatterException.fromJavacDiagnostics(FormatterException.java:50)
        at com.google.googlejavaformat.java.RemoveUnusedImports.parse(RemoveUnusedImports.java:253)
        at com.google.googlejavaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:211)
        at com.google.googlejavaformat.java.Formatter.formatSourceAndFixImports(Formatter.java:219)
        at com.azure.autorest.Javagen.lambda$processInternal$1(Javagen.java:100)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

If i repeat this, the error appears for another class `GroupIdProvisioningState.java`.

If this is a problem with the spec, at least the error should point to a problem in spec and not raise these exceptions.

-

**Comment by weidongxu-microsoft** [comment]
You can use the "skip-formatting" to skip the formatting and see what's wrong with the outputted file.

But mgmt lib is not generated from your input parameters, see https://github.com/Azure/azure-sdk-for-java/wiki/%5BManagement%5D--OpenAPI-specs
parameters somehow like these https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2011031&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=dee4e6ec-be1b-5671-4678-ab293b4004c5

**Comment by dermoritz** [comment]
thanks for this: indeed --skip-formatting helped and pointed to the problem: the "for" in my name space made the code invalid. Really stupid failure on my side :-P - so you can close this
