### ISSUE TITLE
Crash in Java emitter

### ISSUE THREAD

**Issue by dargilco** [Azure/autorest.java#2345]
I run this command at the root of the azure-rest-api-specs repo:
```
pwsh .\eng\scripts\TypeSpec-Generate-Sdk.ps1 -SdkRepoRootDirectory ..\sdk-repos\azure-sdk-for-java -TypeSpecProjectDirectory .\specification\cognitiveservices\Vision.ImageAnalysis -SdkLanguage java
```
Per the screen spew I see
```console
Emitter "@azure-tools/typespec-java" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.java/issues
```
so I'm filing this issue. Note that my TypeSpec files are not yet in Main branch of azure-rest-api-specs. They are in [draft PR](https://github.com/Azure/azure-rest-api-specs/pull/26146) in the topic branch [dargilco/image-analysis-typespec](https://github.com/Azure/azure-rest-api-specs/tree/dargilco/image-analysis-typespec)

Full screen spew

```console
e:\src\azure-rest-api-specs>pwsh .\eng\scripts\TypeSpec-Generate-Sdk.ps1 -SdkRepoRootDirectory ..\sdk-repos\azure-sdk-for-java -TypeSpecProjectDirectory .\specification\cognitiveservices\Vision.ImageAnalysis -SdkLanguage java
Generating java sdk code ...
Using module powershell-yaml with version 0.4.7.
WARNING: Parameter of Commithash or RepoUrl are not provided along with the local path of tspconfig.yaml, trying to re-generate sdk code based on the local type specs.
Generating sdk code based on local type specs at specRepoRoot: E:/src/azure-rest-api-specs.
WARNING: Failed to find tsp-location.yaml in 'E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis'. Trying to create tsp-location.yaml using HEAD commit of the local spec repo then proceed the sdk generation based upon local typespecs at E:/src/azure-rest-api-specs. Alternatively, please make sure to provide CommitHash and RepoUrl parameters when running this script.
WARNING: Failed to find git origin repo of the local spec repo at specRepoRoot: E:/src/azure-rest-api-specs. Using default repo: Azure/azure-rest-api-specs
created package folder E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis
creating tsp-location.yaml in E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis
updated tsp-location.yaml commit to 11368178fde048abf9faecb562407538f04098ff
updated tsp-location.yaml repo to Azure/azure-rest-api-specs
updated tsp-location.yaml directory to specification/cognitiveservices/Vision.ImageAnalysis
updated tsp-location.yaml additionalDirectories to
finished updating tsp-location.yaml in E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis
Calling TypeSpec-Project-Sync.ps1
Using module powershell-yaml with version 0.4.7.
Reading configuration from E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis\tsp-location.yaml
Copying spec from E:\src\azure-rest-api-specs\specification\cognitiveservices\Vision.ImageAnalysis to E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis/TempTypeSpecFiles
Calling TypeSpec-Project-Generate.ps1
Using module powershell-yaml with version 0.4.7.
Reading configuration from E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis\tsp-location.yaml
Generating from E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis\TempTypeSpecFiles\Vision.ImageAnalysis
Copying package.json from E:\src\sdk-repos\azure-sdk-for-java\eng\common\scripts\..\..\emitter-package.json
> npm install
Command succeeded (00:00:08.7880166)

npx tsp compile E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis\TempTypeSpecFiles\Vision.ImageAnalysis\main.tsp --emit @azure-tools/typespec-java --option @azure-tools/typespec-java.emitter-output-dir=E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis/
Exception in thread "main" java.lang.IllegalStateException: Model type not found for type BinaryData and value {}
        at com.azure.autorest.util.ModelExampleUtil.parseNode(ModelExampleUtil.java:176)
        at com.azure.autorest.util.ModelExampleUtil.parseNodeFromMethodParameter(ModelExampleUtil.java:357)
        at com.azure.autorest.util.ModelExampleUtil.parseNodeFromParameter(ModelExampleUtil.java:261)
        at com.azure.autorest.template.example.ClientMethodExampleWriter.parseNodeFromParameter(ClientMethodExampleWriter.java:314)
        at com.azure.autorest.template.example.ClientMethodExampleWriter.lambda$new$0(ClientMethodExampleWriter.java:56)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.azure.autorest.template.example.ClientMethodExampleWriter.<init>(ClientMethodExampleWriter.java:57)
        at com.azure.autorest.template.ClientMethodSampleTemplate.write(ClientMethodSampleTemplate.java:44)
        at com.azure.autorest.model.javamodel.JavaPackage.addClientMethodExamples(JavaPackage.java:229)
        at com.azure.autorest.Javagen.writeToTemplates(Javagen.java:218)
        at com.azure.autorest.TypeSpecPlugin.processTemplates(TypeSpecPlugin.java:55)
        at com.azure.typespec.Main.main(Main.java:91)
Emitter "@azure-tools/typespec-java" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.java/issues

Error: JAR ended with code '1'.
    at ChildProcess.<anonymous> (file:///E:/src/sdk-repos/azure-sdk-for-java/sdk/cognitiveservices/azure-ai-vision-imageanalysis/TempTypeSpecFiles/Vision.ImageAnalysis/node_modules/@azure-tools/typespec-java/dist/src/emitter.js:96:37)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

--------------------------------------------------
Library Version                0.8.13
TypeSpec Compiler Version      0.49.0
--------------------------------------------------
Write-Error: E:\src\azure-rest-api-specs\eng\scripts\TypeSpec-Generate-Sdk.ps1:92
Line |
  92 |      . $commonScript -TypeSpecProjectDirectory $TypeSpecProjectDirecto …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to generate sdk project at E:\src\sdk-repos\azure-sdk-for-java\sdk\cognitiveservices\azure-ai-vision-imageanalysis
```

**Comment by dargilco** [comment]
Additional notes:

- My azure-rest-api-specs topic branch is rebased to Main branch
- My azure-sdk-for-java is on latest Main branch
- The crash still happens even after editing \sdk-repos\azure-sdk-for-java\eng\emitter-package.json to use the latest package for azure-tools/typespec-java (0.9.0 instead of 0.8.13)

**Comment by weidongxu-microsoft** [comment]
0.10.0 should have fixed this
