### ISSUE TITLE
Regenerating EventGrid with latest versions fails on java 17

### ISSUE THREAD

**Issue by billwert** [Azure/autorest.java#2453]
In EventGrid I have a customization:

https://github.com/Azure/azure-sdk-for-java/blob/83e508e207201ad49d364abd8cc1537916e44264/sdk/eventgrid/azure-messaging-eventgrid/swagger/src/main/java/EventGridCustomization.java#L395

When using 4.1.25 of autorest.java on Java 17, I get a failure:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Method String isRecursive( does not exist in class StorageDirectoryDeletedEventData
        at com.azure.autorest.customization.Customization.run(Customization.java:52)
        at com.azure.autorest.postprocessor.Postprocessor.postProcess(Postprocessor.java:99)
        at com.azure.autorest.Javagen.processInternal(Javagen.java:90)
        at com.azure.autorest.extension.base.plugin.NewPlugin.process(NewPlugin.java:214)
        at com.azure.autorest.Main.lambda$main$1(Main.java:15)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$dispatch$2(Connection.java:141)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$process$3(Connection.java:245)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

If I switch to Java 11, it works.

repro:
1) Build EventGrid
2) In `sdk\eventgrid\azure-messaging-eventgrid\swagger`, run `autorest readme.md`

**Comment by weidongxu-microsoft** [comment]
When I was running regen on OpenAI via typespec-java under Java 21, the JAR part seems running forever.

Not urgent, just it occurred to me that customization could be the cause, after half an hour :-)
