### ISSUE TITLE
ClassCustomization addMethod(String method) throws IllegalArgumentException

### ISSUE THREAD

**Issue by jairmyree** [Azure/autorest.java#2706]
When adding a new method using `addMethod(String method)`, I get an `IllegalArgumentException` stating that the method I'm attempting to add does not exist. This should not be the case since the goal is to add a method that does not yet exist.

Autorest Customization:

```keyCustomization.addMethod("/**\n" +
                "     * Get the applicationId property: An AAD Application ID that was granted the required access permissions to the\n" +
                "     * Azure Key Vault that is to be used when encrypting your data at rest. The Application ID should not be confused\n" +
                "     * with the Object ID for your AAD Application.\n" +
                "     * \n" +
                "     * @return the applicationId value.\n" +
                "     */\n" +
                "    public String getApplicationId() {\n" +
                "        return (this.accessCredentials == null) ? null : this.accessCredentials.getApplicationId();\n" +
                "    }");
```

Autorest Output:

```Caused by: java.lang.IllegalArgumentException: Method public String getApplicationId() does not exist in class SearchResourceEncryptionKey
        at com.azure.autorest.customization.ClassCustomization.getMethod(ClassCustomization.java:177)
        at com.azure.autorest.customization.ClassCustomization.lambda$addMethod$10(ClassCustomization.java:410)
        at com.azure.autorest.customization.implementation.Utils.addImports(Utils.java:498)
        at com.azure.autorest.customization.ClassCustomization.addMethod(ClassCustomization.java:410)
        at com.azure.autorest.customization.ClassCustomization.addMethod(ClassCustomization.java:373)
        at SearchServiceCustomizations.customizeSearchResourceEncryptionKey(SearchServiceCustomizations.java:363)
        at SearchServiceCustomizations.customize(SearchServiceCustomizations.java:68)
        at com.azure.autorest.customization.Customization.run(Customization.java:48)
        ... 11 more```

**Comment by weidongxu-microsoft** [comment]
This could be intermittent, would again try work?

If retry not work, please give your branch and command line so we can reproduce.

@alzimmermsft for awareness.

**Comment by jairmyree** [comment]
@weidongxu-microsoft @alzimmermsft It was consistent for me, but I'm not sure if it's consistent for other environments.

**Comment by alzimmermsft** [comment]
@jairmyree could you include the Java version, full stack trace, and a reproduction for this and I should be able to track this down and resolve this.
