### ISSUE TITLE
FATAL: System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#272]
Repro:
```sh
$ autorest --java \
  --use=https://github.com/Azure/autorest.java/releases/download/v2.0.22/microsoft.azure-autorest.java-2.0.22.tgz \
  --input-file=https://raw.githubusercontent.com/Picturepark/Picturepark.SDK.Playground/master/swagger/PictureparkSwaggerAutoRest.json \
  --output-folder=. 
```

Error:
```sh
AutoRest code generation utility [version: 2.0.4280; node: v10.4.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (2.0.4283).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      '/Users/rigibson/.autorest/@microsoft.azure_autorest-core@2.0.4283/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (https://github.com/Azure/autorest.java/releases/download/v2.0.22/microsoft.azure-autorest.java-2.0.22.tgz->2.0.22)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (~2.0.0->2.0.21)
FATAL: System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at AutoRest.Java.JavaCodeGenerator.Generate(CodeModel codeModel) in /Users/rigibson/src/autorest.java/src/JavaCodeGenerator.cs:line 279
   at AutoRest.Java.Program.<ProcessInternal>d__3.MoveNext() in /Users/rigibson/src/autorest.java/src/Program.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: java/generate - FAILED
FATAL: Error: Plugin java reported failure.
Process() cancelled due to exception : Plugin java reported failure.
  Error: Plugin java reported failure.
```

The offending line:
https://github.com/Azure/autorest.java/blob/runtime-v2/src/JavaCodeGenerator.cs#L279

**Comment by RikkiGibson** [comment]
Any clue what this could be about @daschult?

**Comment by daschult** [comment]
It could be that previously `folderWithGeneratedFiles` started with the `folderPrefix`, but for some reason it doesn't now? You could change that expression so that it only does the substring() call if `folderWithGeneratedFiles` starts with `folderPrefix`.

**Comment by jianghaolu** [comment]
Should be fixed in v4 codegen now.
