### ISSUE TITLE
Getting NotImplemented exception during AppService code generation

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest.java#276]
Getting `Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.` while trying to regen appservice in azure-sdk-for-java with following command `gulp codegen --projects appservice/resource-manager --autorest-java D:\GitHub\autorest.java` with the local latest autorest.java sources. Full call stack
```
D:\GitHub\azure-sdk-for-java>gulp codegen --projects appservice/resource-manager --autorest-java D:\GitHub\autorest.java
[14:52:18] Using gulpfile D:\GitHub\azure-sdk-for-java\gulpfile.js
[14:52:18] Starting 'codegen'...
Generating up to 8 projects in parallel..
Generating "appservice/resource-manager" from spec file https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/web/resource-manager/readme.md
Command: autorest ---version=latest https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/web/resource-manager/readme.md --java  --azure-arm  --azure-libraries-for-java-folder=D:\GitHub\azure-sdk-for-java  --license-header=MICROSOFT_MIT_NO_CODEGEN --use=D:\GitHub\autorest.java  --fconfig='{"\"moduleName\"":"\"AppService\""}'  --multiapi --fluent
AutoRest code generation utility [version: 2.0.4283; node: v9.4.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\hovsepm\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading local AutoRest extension '@microsoft.azure/autorest.java' (D:\GitHub\autorest.java)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
Processing batch task - {"tag":"package-2018-02"} .

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at AutoRest.Java.Azure.Fluent.Model.OtherMethods.<FilteredMethodImpls>d__14.MoveNext() in D:\GitHub\autorest.java\src\azurefluent\Model\FluentCommon\OtherMethods\OtherMethods.cs:line 374
   at AutoRest.Java.Azure.Fluent.Model.GeneralizedOutput.<get_MethodImpl>d__20.MoveNext() in D:\GitHub\autorest.java\src\azurefluent\Model\FluentCommon\FluentMethodGroup\GeneralizedOutput.cs:line 149
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at AutoRest.Java.Azure.Fluent.Model.FluentMethodGroupImpl.<get_GeneralizedMethodImpls>d__30.MoveNext() in D:\GitHub\autorest.java\src\azurefluent\Model\FluentCommon\FluentMethodGroup\FluentMethodGroupImpl.cs:line 185
   at AutoRest.Java.Azure.Fluent.Model.ActionOrChildAccessorOnlyMethodGroupImpl.<get_JavaMethods>d__8.MoveNext() in D:\GitHub\autorest.java\src\azurefluent\Model\FluentCommon\ActionOrChildAccessorOnlyMethodGroupImpl.cs:line 59
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoRest.Java.azurefluent.Templates.FluentCommon.ActionOrChildAccessorOnlyMethodGroupImplTemplate.<ExecuteAsync>d__1.MoveNext() in D:\GitHub\autorest.java\src\obj\Razor\azurefluent\Templates\FluentCommon\ActionOrChildAccessorOnlyMethodGroupImplTemplate.cshtml:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in D:\GitHub\autorest.java\autorest.common\src\CodeGenerator.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Java.Azure.Fluent.CodeGeneratorJvaf.<>c__DisplayClass6_0.<<Generate>b__1>d.MoveNext() in D:\GitHub\autorest.java\src\azurefluent\CodeGeneratorJvaf.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
FATAL: java/generate - FAILED
FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.java' terminated.
Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.java' terminated.
Failure during batch task - {"tag":"package-2018-02"} -- false.
(node:43888) UnhandledPromiseRejectionWarning: Error: spawn autorest ---version=latest https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/web/resource-manager/readme.md --java  --azure-arm  --azure-libraries-for-java-folder=D:\GitHub\azure-sdk-for-java  --license-header=MICROSOFT_MIT_NO_CODEGEN --use=D:\GitHub\autorest.java  --fconfig='{"\"moduleName\"":"\"AppService\""}'  --multiapi --fluent ENOENT
    at notFoundError (D:\GitHub\azure-sdk-for-java\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\GitHub\azure-sdk-for-java\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\GitHub\azure-sdk-for-java\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:43888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jianghaolu** [comment]
Seems like it was fixed.
