### ISSUE TITLE
FATAL: System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest.java#322]
Repro: 

Use "azure-rest-api-specs/specification/consumption/resource-manager/readme.md" & tag: "package-2017-12-preview"

Error:

```
Processing batch task - {"tag":"package-2017-12-preview"} .
FATAL: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at AutoRest.Java.Azure.Fluent.Model.FluentModelDisambiguatedMemberVariables.get_MemberVariableAccessorHoldingResourceName() in C:\code\net\autorest.java\src\azurefluent\Model\FluentCommon\ModelMemberVariables\FluentModelDisambiguatedMemberVariables.cs:line 187
   at AutoRest.Java.Azure.Fluent.Model.ClientFluentNonGroupableTopLevelModelImpl.get_MemberVariableAccessorHoldingResourceName() in C:\code\net\autorest.java\src\azurefluent\Model\NonGroupableTopLevelResource\ClientFluentNonGroupableTopLevelModelImpl.cs:line 286
   at AutoRest.Java.Azure.Fluent.Model.ClientFluentNonGroupableTopLevelModelImpl.<get_CtrImplementations>d__23.MoveNext() in C:\code\net\autorest.java\src\azurefluent\Model\NonGroupableTopLevelResource\ClientFluentNonGroupableTopLevelModelImpl.cs:line 212
   at AutoRest.Java.Azure.Fluent.Model.ClientFluentNonGroupableTopLevelModelImpl.<get_JavaMethods>d__21.MoveNext() in C:\code\net\autorest.java\src\azurefluent\Model\NonGroupableTopLevelResource\ClientFluentNonGroupableTopLevelModelImpl.cs:line 180
   at AutoRest.Java.azurefluent.Templates.NonGroupableTopLevelResource.NonGroupableTopLevelModelImplTemplate.<ExecuteAsync>d__1.MoveNext() in C:\code\net\autorest.java\src\obj\Razor\azurefluent\Templates\NonGroupableTopLevelResource\NonGroupableTopLevelModelImplTemplate.cshtml:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in C:\code\net\autorest.java\autorest.common\src\CodeGenerator.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Java.Azure.Fluent.CodeGeneratorJvaf.<Generate>d__6.MoveNext() in C:\code\net\autorest.java\src\azurefluent\CodeGeneratorJvaf.cs:line 149
```

**Comment by jianghaolu** [comment]
Please try the new v4 generator and reopen if it's still an issue.
